{% set name = "beanie" %}
{% set version = "1.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/roman-right/beanie/archive/refs/tags/{{ version }}.tar.gz
  sha256: 3a1bcd60a8c8d90fa725d3e8956fc723f6df4d5fe777ca8f932344031c170b54

build:
  entry_points:
    - beanie = beanie.executors.migrate:migrations
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.7
  run:
    - click >=7
    - motor >=2.5,<4.0
    - pydantic >=1.10.0
    - python >=3.7
    - toml
    - lazy-model >=0.0.3

test:
  imports:
    - beanie
  commands:
    - pip check
    - beanie --help
  requires:
    - pip

about:
  home: https://roman-right.github.io/beanie/
  dev_url: https://github.com/roman-right/beanie
  summary: Asynchronous Python ODM for MongoDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
