{% set name = "beanie" %}
{% set version = "1.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/roman-right/beanie/archive/refs/tags/{{ version }}.tar.gz
  sha256: e0e60a75973f4eb7bacb4f8f3094666b74c5ecad9a48ac7bd73b3e974f12eae7
  patches:
    - lazy-model.patch

build:
  entry_points:
    - beanie = beanie.executors.migrate:migrations
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - flit-core
    - python >=3.7
  run:
    - click >=7
    - motor >=2.5,<4.0
    - pydantic >=1.10.0,<2
    - python >=3.7
    - toml
    - lazy-model >=0.1.0

test:
  imports:
    - beanie
  commands:
    - pip check
    - beanie --help
  requires:
    - pip

about:
  home: https://roman-right.github.io/beanie/
  dev_url: https://github.com/roman-right/beanie
  summary: Asynchronous Python ODM for MongoDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
