{% set name = "beanie" %}
{% set version = "1.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/roman-right/beanie/archive/refs/tags/{{ version }}.tar.gz
  sha256: 402da17a3c53520065a6b95916e70bb59a669f9e7b2768371c330a4eafd04d00

build:
  entry_points:
    - beanie = beanie.executors.migrate:migrations
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - click >=7
    - motor >=2.5,<4.0
    - pydantic >=1.9.0
    - python >=3.6
    - toml
    - yarl >=1.6

test:
  imports:
    - beanie
  commands:
    - pip check
    - beanie --help
  requires:
    - pip

about:
  home: https://roman-right.github.io/beanie/
  dev_url: https://github.com/roman-right/beanie
  summary: Asynchronous Python ODM for MongoDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
